### ISSUE TITLE
[question] security fix for http-cache-semantics 4.1.1 in v8

### ISSUE THREAD

**Issue by arnulfojr** [jaredwray/cacheable-request#225]
**Describe the "bug"**

This is not really a bug report but rather a reach out. It seems that the recent PR https://github.com/jaredwray/cacheable-request/pull/224 that mitigates a security vulnerability of the http-cache-semantics (4.1.1) is not present in a release that supports CJS.

I believe this is blocking the adoption of the security fix on got v11 (non-ESM) - https://github.com/sindresorhus/got/issues/2220

I acknowledge that support for [v8 has ended](https://github.com/jaredwray/cacheable-request/blob/main/SECURITY.md) but I'm reaching it as a consultation if it's possible to fix this for the libraries using CJS.

If this is not possible feel free to close the issue.

https://github.com/jaredwray/cacheable-request/security/advisories/GHSA-8x6c-cv3v-vp6g

**Comment by dscalzi** [comment]
This absolutely should be backported, it is not possible in many circumstances to move to ESM due to lopsided support in the JS ecosystem. It's a fantasy to force everyone off CJS when many major libraries are still not esm compatible.

**Comment by MLSTRM** [comment]
As a slight aside to the backporting I have a further related question.
Older versions of this library are already enforcing use of http-cache-semantincs@^4.0.0, which is a compatible version range with the fixed version of the library, and while not a strict guarantee, this combined with npm audit/yarn audit should mean that its sufficient to use the version of the transient dependency to identify if there is a present issue, rather than also marking old versions of this library as directly vulnerable? (As it is possible to upgrade the version of http-cache-semantics in use while still remaining compatible here)
Again while it would be nice to force everything always to use the newest versions of things this is not always practical, but I think the vulnerability entry here is slightly misleading as it is not an issue in this library itself but a transient dependency.

**Comment by paulius-valiunas** [comment]
The GHSA shouldn't be updated, it should be deleted. There is already a CVE registered on `http-cache-semantics` itself, there's no need to file a new CVE for each package that uses it.

**Comment by paulius-valiunas** [comment]
@jaredwray please remove the advisory, thank you.

**Comment by sseide** [comment]
@jaredwray Yes - please remove this misleading advisory.

There is no vulnerability in your own package, only in one dependency - and this dependency already has an advisory flagged by "npm audit" and other security scanners.

Due to your advisory all security scanner will error out with a false positive. Example:

application has "got" with latest 11.x version as dependency.
"got@11.8.6" depends on "cacheable-request@7.0.2" depends on "http-cache-semantics@^4.0.0"
Now the app might use the insecure "http-cache-semantics@4.1.0" but an simple `npm update http-cache-semantics` resolves this because your lib allows secured 4.1.1 too via its semver range. Therefore no need to update "got" or your library - we are secure now. But Scanner do not reflect this because they thing your library is vulnerable (and this is wrong).

**Comment by noppa** [comment]
Yeah... If there's a vulnerability in, say, lodash, we don't go around creating unique advisories for each package that has lodash as a dependency, that would be chaotic.

**Comment by phawxby** [comment]
Agree, I just didn't comment in the best place.
https://github.com/jaredwray/cacheable-request/pull/226#issuecomment-1427838687

**Comment by jaredwray** [comment]
All - I have asked Github via support to remove the advisory as it was done by mistake. Again, very sorry for the confusion here as we have been working since last Friday to get that advisory removed with Github support. 

On the v8. I am willing to do the update on v8 and get a version pushed to update this even though we no longer support it. It is one of the reasons why we have the commonjs branch still as many people are still affected.

**Comment by jaredwray** [comment]
@paulius-valiunas thanks for the update on that and yes that would be the case. Going to close this pull request.

**Comment by arnulfojr** [comment]
Thanks everybody involved to get this resolved!

**Comment by jaredwray** [comment]
Just FYI that github support has removed it and it is all fixed now.
